### ISSUE TITLE
Object JSON is incorrect

### ISSUE THREAD

**Issue by random42** [adaltas/node-csv-stringify#117]
I'm using version 5.3.6, but tried also on 5.5.1

When serializing an object the JSON output is incorrect:

```javascript
const csvStringify = require('csv-stringify');

const data = [
  {
    x: 'asd',
    y: {
      a: 1,
      b: '2'
    },
  }
];

csvStringify(data, {
  cast: {
    //object: JSON.stringify
  }
}, (err, s) => {
  console.log(s);
});
```

Output:
```csv
asd,"{""a"":1,""b"":""2""}"
```

Even when option `quoted` is false (by default). Even when passing `JSON.stringify` as `cast.object` option, same result.

**Comment by wdavidw** [comment]
Please provide a complete example on how you are using the library.

**Comment by wdavidw** [comment]
By the way, this is not JSON, it is just an JS object literal. JSON is a string.

**Comment by random42** [comment]
> Please provide a complete example on how you are using the library.

I edited the issue so you can try it yourself

**Comment by wdavidw** [comment]
This library is about generating CSV, which is tabular and not hierarchical. When it encounters an object literal, the default is to serialise to JSON because there is not much else we can do. Of course, this JSON is a field of our final CSV and must be escaped to produce valid CSV. I don't see anything wrong with your code provided above.

**Comment by random42** [comment]
My fault, sorry. I thought it was only a matter of escaping the separator character with something like \

I still don't understand how that escaping works but csv parsers get it somehow, so that's enough.
