### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by igor-savin-ht** [adaltas/node-csv-stringify#54]
It would be much more convenient to use csv-stringify if it supported returning result via promise.

We can provide PR if this change is approved.

**Comment by igor-savin-ht** [comment]
@wdavidw How promise wrapper can affect memory usage in any way? All it would do is call resolve method as a callback for the stringify method and that's it.

**Comment by wdavidw** [comment]
Promise is here for async execution. CSV parsing/stringifying is not async by nature. Either you have a big data source, in which case you must use the Stream API to treat chunks of your data source, or you have a source which fit in memory, in which case you can use the "csv-stringify/lib/sync" module.

**Comment by igor-savin-ht** [comment]
@wdavidw Please don't close this issue just yet, I am fully prepared to update documentation if that is the most appropriate course of actions.

However, I am trying to understand first. So what you are saying is that callback API is not actually async, under-the-hood it is still executing conversion synchronously in the same thread? Then why implement it via callback in the first place and not just expose the sync method itself?

I'll create a PR with documentation clarification after I understand the idea behind it all myself :).

**Comment by wdavidw** [comment]
You are right, this question is poping over and over and we need to clarify. I'll enthousiastically welcome a pull request enhancing the doc. Note, the same question apply to "csv-parse".

Yes, all the work is done in one function, run synchronously, which can be called one time (sync mode) or multiple times (stream mode, potentionally async mode).

So there are two ways to use this lib:

sync: `full data set -> require('csv-stringify/lib/sync') 1 time -> return full result set`
async: `readable stream -> require('csv-stringify') x times -> return writable stream`

Then why are we providing a callback approach, basically when the source is a readable stream and you wish to retrieve the full data set: `readable stream -> require('csv-parse') x times -> callback with full result set`.

You could argue that the same approache could be used to return a promise instead of returning a promise: `readable stream -> require('csv-parse') x times -> return promise with full result set`. However, this is incompatible with the API since we are already returned a writable stream, which is the recommand approach since it is the only scalable one. Additionnaly, most people requesting promise were not concerned with streaming and scalability and in reality wanted to use the "csv-stringify/lib/sync" module. I dont see necessary to provide the "csv-stringify/lib/promise" module for this corner case usage which will also confuse users with the usage of an asynchrous API (Node.js stream) inside a naturally synchronous usecase (CSV parsing). Alternatively, users could use the `util.promisify` native function (Node.js >= v8.0.0).

**Comment by igor-savin-ht** [comment]
Created a PR, please review!

**Comment by igor-savin-ht** [comment]
@wdavidw Are there any outstanding issues with the PR after the last round of tweaks?

**Comment by wdavidw** [comment]
No, I'm good to merge it. However, it seems like the modifications are stuck into your fork, github doesnt propose me to merge it.

**Comment by jpike88** [comment]
So uh... what happened to this?

**Comment by nanomosfet** [comment]
I just did the following to promisify my csv-stringify
```javascript
function promiseStringify(someReleventdata, options) {
  return new Promise((resolve, reject) => {
    stringify(someReleventData, options, (err, output) => {
      if (err) {
        reject(err)
      } else {
        resolve(output)
      }
    }
  }
}
```

**Comment by yonilerner** [comment]
@nanomosfet The whole point of what @wdavidw is saying is that if youre just going to do that you might as well use the sync API. There is literally no point whatsoever in promisifying a *synchronous* process

**Comment by nanomosfet** [comment]
@yonilerner in some cases wrapping it in a promise helps when using it with other promises in your code. The call back method also makes it look a bit less readable. Inherently, everything in is going through the same thread so we always promisify synchronous things. Its just added to the event stack at a different time.

**Comment by jpike88** [comment]
Ok so the issue here seems to be clarity of documentation. Only looking now do I realise there is a sync module, but the typescript definitions don’t appear to reference it.

**Comment by yonilerner** [comment]
https://github.com/adaltas/node-csv-stringify/blob/master/lib/sync.d.ts

**Comment by wdavidw** [comment]
Closing since there is no more activty, note, a new website was introduced in the mean time.
